### ISSUE TITLE
Moving the shim detection to outside of the bindings

### ISSUE THREAD

**Issue by fidian** [tests-always-included/angular-placeholder#11]
@vitvad offered pull request #10 to improve performance in modern browsers.  I've opened this issue for further discussion because I am unable to reopen the pull request.

vitvad - could you explain more about your patch and how it helps?

**Comment by vitvad** [comment]
@fidian Hi,
I just move to top `if (needsShim) { ` line - you need plaseholder shim only for IE8-9 
but in chrome you directive currently also work, just check you example https://jsfiddle.net/y78ohbuw/1/embedded/result/ in chrome 2 bottom fields has both placeholder and text

**Comment by fidian** [comment]
One of the points of the placeholder module is to toggle a class that also allows for easier styling.  If I move the `if` up that high, I eliminate the toggles for the class.

**Comment by vitvad** [comment]
@fidian , why you need this class toggling for browsers that support placeholder ?
I thought this is kind like shim for placeholder support

**Comment by fidian** [comment]
Without the shim in newer browsers you are able to style the text.  The CSS selector is per-browser, which is irritating.

In older browsers you can not style the placeholder text with a CSS selector.  Thus if I use the shim, I also want to make it possible to style the placeholder text.

To achieve the utmost in simplicity for the user, the placeholder class is added and removed.  That way there is a single, uniform way of styling the input.

**Comment by fidian** [comment]
Closing issue because the shim provides two benefits and the proposed change negates one of those benefits.
