### ISSUE TITLE
NPM publish

### ISSUE THREAD

**Issue by mistic100** [tests-always-included/angular-placeholder#16]
Hello

can you publish version 1.0.3 on npm ?

**Comment by mistic100** [comment]
Would be cool too to change the main file to index.js with this content

```js
require('./lib/tai-placeholder');
module.exports = 'taiPlaceholder';
```

For beter integration with webpack

**Comment by fidian** [comment]
Published.

Why doesn't webpack read my `package.json` file and use the `main` entrypoint?

I'm closing this because it was opened so I would publish 1.0.3 in NPM. I would encourage you to open a new issue to discuss better webpack integration.
