### ISSUE TITLE
Placeholder class is not removed on input[type='email']

### ISSUE THREAD

**Issue by oliverbenns** [tests-always-included/angular-placeholder#5]
Any text added to the input is also treated as a placeholder (is removed when refocused).

**Comment by fidian** [comment]
I made a change that works for me - could you test the issue-5 branch to see how well it works for you?

**Comment by CullenShane** [comment]
Issue-5 branch is working quite nicely for this issue.

**Comment by vitvad** [comment]
Issue-5 branch fix this issue and seems fix issues/9

**Comment by fidian** [comment]
Merged.
